//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SARVA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Pedido
    {
        public int codigo_IV { get; set; }
        public int id_ciclo_IV { get; set; }
        public int id_venda_IV { get; set; }
        public int id_pedido { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual Item_Venda Item_Venda { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
